// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.pb.server.sdk.filter;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 type = 1;</code>
     */
    int getType();

    /**
     * <code>optional int64 msg_id = 2;</code>
     */
    long getMsgId();

    /**
     * <code>optional int64 time = 3;</code>
     */
    long getTime();

    /**
     * <code>optional string r_uid = 4;</code>
     */
    String getRUid();
    /**
     * <code>optional string r_uid = 4;</code>
     */
    com.google.protobuf.ByteString
        getRUidBytes();

    /**
     * <code>optional string s_uid = 5;</code>
     */
    String getSUid();
    /**
     * <code>optional string s_uid = 5;</code>
     */
    com.google.protobuf.ByteString
        getSUidBytes();

    /**
     * <code>optional int64 session_id = 6;</code>
     */
    long getSessionId();

    /**
     * <code>optional string msg = 7;</code>
     */
    String getMsg();
    /**
     * <code>optional string msg = 7;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional bytes file = 8;</code>
     */
    com.google.protobuf.ByteString getFile();

    /**
     * <code>optional string file_name = 9;</code>
     */
    String getFileName();
    /**
     * <code>optional string file_name = 9;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>optional string file_type = 10;</code>
     */
    String getFileType();
    /**
     * <code>optional string file_type = 10;</code>
     */
    com.google.protobuf.ByteString
        getFileTypeBytes();

    /**
     * <code>optional int64 file_length = 11;</code>
     */
    long getFileLength();
  }
  /**
   * Protobuf type {@code MessageProto}
   */
  public  static final class MessageProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageProto)
      MessageProtoOrBuilder {
    // Use MessageProto.newBuilder() to construct.
    private MessageProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageProto() {
      type_ = 0;
      msgId_ = 0L;
      time_ = 0L;
      rUid_ = "";
      sUid_ = "";
      sessionId_ = 0L;
      msg_ = "";
      file_ = com.google.protobuf.ByteString.EMPTY;
      fileName_ = "";
      fileType_ = "";
      fileLength_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MessageProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 16: {

              msgId_ = input.readInt64();
              break;
            }
            case 24: {

              time_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              rUid_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              sUid_ = s;
              break;
            }
            case 48: {

              sessionId_ = input.readInt64();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 66: {

              file_ = input.readBytes();
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              fileType_ = s;
              break;
            }
            case 88: {

              fileLength_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProtos.internal_static_MessageProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProtos.internal_static_MessageProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageProto.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int MSG_ID_FIELD_NUMBER = 2;
    private long msgId_;
    /**
     * <code>optional int64 msg_id = 2;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <code>optional int64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int R_UID_FIELD_NUMBER = 4;
    private volatile Object rUid_;
    /**
     * <code>optional string r_uid = 4;</code>
     */
    public String getRUid() {
      Object ref = rUid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rUid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string r_uid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRUidBytes() {
      Object ref = rUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S_UID_FIELD_NUMBER = 5;
    private volatile Object sUid_;
    /**
     * <code>optional string s_uid = 5;</code>
     */
    public String getSUid() {
      Object ref = sUid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sUid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string s_uid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSUidBytes() {
      Object ref = sUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSION_ID_FIELD_NUMBER = 6;
    private long sessionId_;
    /**
     * <code>optional int64 session_id = 6;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }

    public static final int MSG_FIELD_NUMBER = 7;
    private volatile Object msg_;
    /**
     * <code>optional string msg = 7;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string msg = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString file_;
    /**
     * <code>optional bytes file = 8;</code>
     */
    public com.google.protobuf.ByteString getFile() {
      return file_;
    }

    public static final int FILE_NAME_FIELD_NUMBER = 9;
    private volatile Object fileName_;
    /**
     * <code>optional string file_name = 9;</code>
     */
    public String getFileName() {
      Object ref = fileName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string file_name = 9;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_TYPE_FIELD_NUMBER = 10;
    private volatile Object fileType_;
    /**
     * <code>optional string file_type = 10;</code>
     */
    public String getFileType() {
      Object ref = fileType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileType_ = s;
        return s;
      }
    }
    /**
     * <code>optional string file_type = 10;</code>
     */
    public com.google.protobuf.ByteString
        getFileTypeBytes() {
      Object ref = fileType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_LENGTH_FIELD_NUMBER = 11;
    private long fileLength_;
    /**
     * <code>optional int64 file_length = 11;</code>
     */
    public long getFileLength() {
      return fileLength_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (msgId_ != 0L) {
        output.writeInt64(2, msgId_);
      }
      if (time_ != 0L) {
        output.writeInt64(3, time_);
      }
      if (!getRUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, rUid_);
      }
      if (!getSUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sUid_);
      }
      if (sessionId_ != 0L) {
        output.writeInt64(6, sessionId_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msg_);
      }
      if (!file_.isEmpty()) {
        output.writeBytes(8, file_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, fileName_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, fileType_);
      }
      if (fileLength_ != 0L) {
        output.writeInt64(11, fileLength_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, msgId_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, time_);
      }
      if (!getRUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, rUid_);
      }
      if (!getSUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sUid_);
      }
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, sessionId_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msg_);
      }
      if (!file_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, file_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, fileName_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, fileType_);
      }
      if (fileLength_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, fileLength_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageProto)) {
        return super.equals(obj);
      }
      MessageProto other = (MessageProto) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && (getMsgId()
          == other.getMsgId());
      result = result && (getTime()
          == other.getTime());
      result = result && getRUid()
          .equals(other.getRUid());
      result = result && getSUid()
          .equals(other.getSUid());
      result = result && (getSessionId()
          == other.getSessionId());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && getFile()
          .equals(other.getFile());
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && getFileType()
          .equals(other.getFileType());
      result = result && (getFileLength()
          == other.getFileLength());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + R_UID_FIELD_NUMBER;
      hash = (53 * hash) + getRUid().hashCode();
      hash = (37 * hash) + S_UID_FIELD_NUMBER;
      hash = (53 * hash) + getSUid().hashCode();
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionId());
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + FILE_FIELD_NUMBER;
      hash = (53 * hash) + getFile().hashCode();
      hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + FILE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFileType().hashCode();
      hash = (37 * hash) + FILE_LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFileLength());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageProto)
        MessageProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProtos.internal_static_MessageProto_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProtos.internal_static_MessageProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageProto.class, Builder.class);
      }

      // Construct using com.pb.server.sdk.filter.MessageProtos.MessageProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        msgId_ = 0L;

        time_ = 0L;

        rUid_ = "";

        sUid_ = "";

        sessionId_ = 0L;

        msg_ = "";

        file_ = com.google.protobuf.ByteString.EMPTY;

        fileName_ = "";

        fileType_ = "";

        fileLength_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProtos.internal_static_MessageProto_descriptor;
      }

      public MessageProto getDefaultInstanceForType() {
        return MessageProto.getDefaultInstance();
      }

      public MessageProto build() {
        MessageProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MessageProto buildPartial() {
        MessageProto result = new MessageProto(this);
        result.type_ = type_;
        result.msgId_ = msgId_;
        result.time_ = time_;
        result.rUid_ = rUid_;
        result.sUid_ = sUid_;
        result.sessionId_ = sessionId_;
        result.msg_ = msg_;
        result.file_ = file_;
        result.fileName_ = fileName_;
        result.fileType_ = fileType_;
        result.fileLength_ = fileLength_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageProto) {
          return mergeFrom((MessageProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageProto other) {
        if (other == MessageProto.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getRUid().isEmpty()) {
          rUid_ = other.rUid_;
          onChanged();
        }
        if (!other.getSUid().isEmpty()) {
          sUid_ = other.sUid_;
          onChanged();
        }
        if (other.getSessionId() != 0L) {
          setSessionId(other.getSessionId());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getFile() != com.google.protobuf.ByteString.EMPTY) {
          setFile(other.getFile());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (!other.getFileType().isEmpty()) {
          fileType_ = other.fileType_;
          onChanged();
        }
        if (other.getFileLength() != 0L) {
          setFileLength(other.getFileLength());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>optional int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long msgId_ ;
      /**
       * <code>optional int64 msg_id = 2;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <code>optional int64 msg_id = 2;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 msg_id = 2;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 3;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 3;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private Object rUid_ = "";
      /**
       * <code>optional string r_uid = 4;</code>
       */
      public String getRUid() {
        Object ref = rUid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          rUid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string r_uid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRUidBytes() {
        Object ref = rUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string r_uid = 4;</code>
       */
      public Builder setRUid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string r_uid = 4;</code>
       */
      public Builder clearRUid() {
        
        rUid_ = getDefaultInstance().getRUid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string r_uid = 4;</code>
       */
      public Builder setRUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rUid_ = value;
        onChanged();
        return this;
      }

      private Object sUid_ = "";
      /**
       * <code>optional string s_uid = 5;</code>
       */
      public String getSUid() {
        Object ref = sUid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sUid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string s_uid = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSUidBytes() {
        Object ref = sUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s_uid = 5;</code>
       */
      public Builder setSUid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s_uid = 5;</code>
       */
      public Builder clearSUid() {
        
        sUid_ = getDefaultInstance().getSUid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s_uid = 5;</code>
       */
      public Builder setSUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sUid_ = value;
        onChanged();
        return this;
      }

      private long sessionId_ ;
      /**
       * <code>optional int64 session_id = 6;</code>
       */
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>optional int64 session_id = 6;</code>
       */
      public Builder setSessionId(long value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 session_id = 6;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>optional string msg = 7;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString file_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes file = 8;</code>
       */
      public com.google.protobuf.ByteString getFile() {
        return file_;
      }
      /**
       * <code>optional bytes file = 8;</code>
       */
      public Builder setFile(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        file_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes file = 8;</code>
       */
      public Builder clearFile() {
        
        file_ = getDefaultInstance().getFile();
        onChanged();
        return this;
      }

      private Object fileName_ = "";
      /**
       * <code>optional string file_name = 9;</code>
       */
      public String getFileName() {
        Object ref = fileName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string file_name = 9;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string file_name = 9;</code>
       */
      public Builder setFileName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string file_name = 9;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string file_name = 9;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private Object fileType_ = "";
      /**
       * <code>optional string file_type = 10;</code>
       */
      public String getFileType() {
        Object ref = fileType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fileType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string file_type = 10;</code>
       */
      public com.google.protobuf.ByteString
          getFileTypeBytes() {
        Object ref = fileType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string file_type = 10;</code>
       */
      public Builder setFileType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string file_type = 10;</code>
       */
      public Builder clearFileType() {
        
        fileType_ = getDefaultInstance().getFileType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string file_type = 10;</code>
       */
      public Builder setFileTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileType_ = value;
        onChanged();
        return this;
      }

      private long fileLength_ ;
      /**
       * <code>optional int64 file_length = 11;</code>
       */
      public long getFileLength() {
        return fileLength_;
      }
      /**
       * <code>optional int64 file_length = 11;</code>
       */
      public Builder setFileLength(long value) {
        
        fileLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 file_length = 11;</code>
       */
      public Builder clearFileLength() {
        
        fileLength_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:MessageProto)
    }

    // @@protoc_insertion_point(class_scope:MessageProto)
    private static final MessageProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageProto();
    }

    public static MessageProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageProto>
        PARSER = new com.google.protobuf.AbstractParser<MessageProto>() {
      public MessageProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageProto> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageProto> getParserForType() {
      return PARSER;
    }

    public MessageProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rMessage.proto\"\302\001\n\014MessageProto\022\014\n\004type" +
      "\030\001 \001(\005\022\016\n\006msg_id\030\002 \001(\003\022\014\n\004time\030\003 \001(\003\022\r\n\005" +
      "r_uid\030\004 \001(\t\022\r\n\005s_uid\030\005 \001(\t\022\022\n\nsession_id" +
      "\030\006 \001(\003\022\013\n\003msg\030\007 \001(\t\022\014\n\004file\030\010 \001(\014\022\021\n\tfil" +
      "e_name\030\t \001(\t\022\021\n\tfile_type\030\n \001(\t\022\023\n\013file_" +
      "length\030\013 \001(\003B)\n\030com.pb.server.sdk.filter" +
      "B\rMessageProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MessageProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageProto_descriptor,
        new String[] { "Type", "MsgId", "Time", "RUid", "SUid", "SessionId", "Msg", "File", "FileName", "FileType", "FileLength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
